version: "3.8"

services:
  api:
    image: eassbhhtgu/homeautomation-api:latest
    entrypoint: bash -c "/usr/sbin/update-ca-certificates && dotnet /app/HomeAutomation.WebApplication.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTPS_PORT: "443"
      ASPNETCORE_URLS: https://+
      ASPNETCORE_Kestrel__Certificates__Default__KeyPath: /run/secrets/localhost.key
      ASPNETCORE_Kestrel__Certificates__Default__Path: /run/secrets/localhost.crt
    ports:
    - 20443:443/tcp
    secrets:
    - source: localhost.crt
    - source: localhost.key
    - source: ca.crt
      target: /usr/local/share/ca-certificates/ca.crt

  website:
    image: eassbhhtgu/homeautomation-website:latest
    depends_on:
    - api
    entrypoint: bash -c "/usr/sbin/update-ca-certificates && dotnet /app/HomeAutomation.Website.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTPS_PORT: "443"
      ASPNETCORE_URLS: https://+
      ASPNETCORE_Kestrel__Certificates__Default__KeyPath: /run/secrets/localhost.key
      ASPNETCORE_Kestrel__Certificates__Default__Path: /run/secrets/localhost.crt
      Backend: https://api/
    ports:
    - 443:443/tcp
    secrets:
    - source: localhost.crt
    - source: localhost.key
    - source: ca.crt
      target: /usr/local/share/ca-certificates/ca.crt

secrets:
  ca.crt:
    file: ${USERPROFILE}\.aspnet\https\ca.crt
  localhost.crt:
    file: ${USERPROFILE}\.aspnet\https\localhost.crt
  localhost.key:
    file: ${USERPROFILE}\.aspnet\https\localhost.key
